#[Get IP Address of Machine running Cloud Build]
- id: 'Curl Cloud Build IP Address'
 name: 'gcr.io/cloud-builders/curl'
 args: ['ipconfig.io','--output','/workspace/ip_addr.txt']
#[Update Master Authorized Networks on GKE Cluster]
- id: 'Add CloudBuild IP Address to Authorized Networks'
 name: 'gcr.io/cloud-builders/gcloud'
 entrypoint: "bash"
 args:
 - '-c'
 - | 
 if [ -d "environments/$BRANCH_NAME/" ]; then
 export ip_addr=$(cat /workspace/ip_addr.txt)
 echo "Cloud Build IP: ${ip_addr}"
